on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test App Code
        run: pytest
